### PR TITLE
update build-number

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
there are missing some template-files which should be available for a updated build. (locally tested)

**Comment by csachs** [comment]
What exactly was/is the problem? Some CI/automated build related issues or is anything with the current package not ok?

**Comment by looooo** [comment]
This one here:
https://github.com/mozman/ezdxf/issues/63

**Comment by looooo** [comment]
I guess rerendering and using newer conda-build solves the issue.

**Comment by csachs** [comment]
Oh, thanks for taking care of this. I'll merge this and check the uploaded package.

**Comment by csachs** [comment]
Unfortunately this didn't fix the problem.

**Comment by looooo** [comment]
It worked for me here:
https://anaconda.org/OpenGlider/ezdxf/files

Maybe we can create a test to make sure the dxf-files are included. We encountered a problem with the old ezdxf-package here:

I guess we could test with something like this:
```
import ezdxf
drawing = ezdxf.new(dxfversion="AC1015")
```

**Pull request merged**
